=== I-am-Vaishnavi/Online-food-delivery-website/Mini project/xml/a.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="class">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="regno" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== I-am-Vaishnavi/Online-food-delivery-website/Mini project/xml/a.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="a.xsl" type="text/xsl"?>
<class xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="a.xsd">
    <student>
        <name>aaaaaaaaaaa</name> 
        <regno>11111111</regno>
       </student>
       <student>
        <name>bbbbbbbb</name> 
        <regno>2222222</regno>
       </student><student>
        <name>ccccccc</name> 
        <regno>33333</regno>
       </student><student>
        <name>dddddd</name> 
        <regno>444444</regno>
       </student>


</class>
